import os
import json
import glob
import re

def clean_text(text):
    """
    Basic cleanup. 
    """
    if not text:
        return ""
    return text.replace('\n', ' ').strip()

def analyze_transcripts():
    transcript_dir = 'transcripts'
    output_report = 'transcript_analysis_report.txt'
    
    files = glob.glob(os.path.join(transcript_dir, '*.json'))
    print(f"Found {len(files)} transcript files.")
    
    results = []
    
    for file_path in files:
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
        except json.JSONDecodeError as e:
            print(f"Error reading {os.path.basename(file_path)}: {e}")
            continue
        except Exception as e:
            print(f"Unexpected error reading {os.path.basename(file_path)}: {e}")
            continue
            
        video_id = data.get('video_id')
        title = data.get('title')
        language = data.get('language')
        is_generated = data.get('is_generated')
        transcript_segments = data.get('transcript', [])
        
        if not transcript_segments:
             full_text = ""
        else:
             # handling loose segments 
             full_text = " ".join([str(s.get('text', '')) for s in transcript_segments])
             
        full_text = clean_text(full_text)
        
        word_count = len(full_text.split())
        
        # Heuristic for "quality"
        has_punctuation = bool(re.search(r'[.!?]', full_text))
        
        results.append({
            'video_id': video_id,
            'title': title,
            'language': language,
            'is_generated': is_generated,
            'word_count': word_count,
            'has_punctuation': has_punctuation,
            'excerpt': full_text[:100] + "..."
        })
        
    # Generate report
    with open(output_report, 'w', encoding='utf-8') as f:
        f.write("Transcript Analysis Report\n")
        f.write("==========================\n\n")
        
        for res in results:
            f.write(f"Title: {res['title']}\n")
            f.write(f"ID: {res['video_id']}\n")
            f.write(f"Language: {res['language']} (Generated: {res['is_generated']})\n")
            f.write(f"Word Count: {res['word_count']}\n")
            f.write(f"Has Punctuation: {res['has_punctuation']}\n")
            f.write(f"Excerpt: {res['excerpt']}\n")
            
            if res['is_generated'] and not res['has_punctuation']:
                 f.write("suggestion: This transcript is autogenerated and lacks punctuation. Run through an LLM for correction.\n")
            
            f.write("-" * 30 + "\n")
            
    print(f"Analysis complete. Processed {len(results)} files. Report saved to {output_report}")

if __name__ == "__main__":
    analyze_transcripts()
